<?php

use Illuminate\Database\Seeder;
use App\Member;

class MembersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $members = [
            [
                'id' => 1,
                'lastname' =>'piwie',
                'firstname' => 'lotte',
                'birthday' => '1986-05-24',
                'gender'=> 'Femme',
                'address' => '8 rue horloge',
                'zipcode' => '92300',
                'city' => 'artie',
                'email' => 'lotte@gmail.com',
                'primaryphone' => '0677657995',
                'secondaryphone' => '',
                'mutual_id' => '4',
                'pension_id' => '10',
            ],
            [
                'id' => 2,
                'lastname' =>'yoyette',
                'firstname' => 'eleonore',
                'birthday' => '1973-12-11',
                'gender'=> 'Femme',
                'address' => '5 rue du four',
                'zipcode' => '70819',
                'city' => 'montageriy',
                'email' => 'marion@gmail.com',
                'primaryphone' => '0145667238',
                'secondaryphone' => '',
                'mutual_id' => '1',
                'pension_id' => '1',
            ],
            [
                'id' => 3,
                'lastname' =>'ivesme',
                'firstname' => 'papi',
                'birthday' => '1933-12-11',
                'gender'=> 'Homme',
                'address' => '8 rue paradis',
                'zipcode' => '09987',
                'city' => 'montageriy',
                'email' => 'papi@gmail.com',
                'primaryphone' => '0145647238',
                'secondaryphone' => '',
                'mutual_id' => '6',
                'pension_id' => '7',
            ],
            [
                'id' => 4,
                'lastname' =>'juins',
                'firstname' => 'lola',
                'birthday' => '1973-02-11',
                'gender'=> 'Femme',
                'address' => '5 rue du four',
                'zipcode' => '70801',
                'city' => 'montageriy',
                'email' => 'juins@gmail.com',
                'primaryphone' => '0145667238',
                'secondaryphone' => '',
                'mutual_id' => '10',
                'pension_id' => '10',
            ],
            [
                'id' => 5,
                'lastname' =>'zerty',
                'firstname' => 'popeye',
                'birthday' => '1945-12-11',
                'gender'=> 'Homme',
                'address' => '5 rue du four',
                'zipcode' => '70801',
                'city' => 'montageriy',
                'email' => 'popeye@gmail.com',
                'primaryphone' => '0145667238',
                'secondaryphone' => '',
                'mutual_id' => '18',
                'pension_id' => '19',
            ],
            [
                'id' => 6,
                'lastname' =>'mailu',
                'firstname' => 'abdu',
                'birthday' => '1986-12-11',
                'gender'=> 'Homme',
                'address' => '5 rue du four',
                'zipcode' => '70801',
                'city' => 'montageriy',
                'email' => 'abdu@gmail.com',
                'primaryphone' => '0145667238',
                'secondaryphone' => '',
                'mutual_id' => '6',
                'pension_id' => '16',
            ],
            [
                'id' => 7,
                'lastname' =>'jonas',
                'firstname' => 'pipa',
                'birthday' => '1990-12-11',
                'gender'=> 'Femme',
                'address' => '5 rue du four',
                'zipcode' => '70801',
                'city' => 'montageriy',
                'email' => 'pipa@gmail.com',
                'primaryphone' => '0145667238',
                'secondaryphone' => '',
                'mutual_id' => '4',
                'pension_id' => '14',
            ],
            [
                'id' => 8,
                'lastname' =>'frani',
                'firstname' => 'fanchon',
                'birthday' => '1973-12-11',
                'gender'=> 'Femme',
                'address' => '5 rue du four',
                'zipcode' => '70801',
                'city' => 'montageriy',
                'email' => 'fanchon@gmail.com',
                'primaryphone' => '0145667238',
                'secondaryphone' => '',
                'mutual_id' => '4',
                'pension_id' => '4',
            ],
            [
                'id' => 9,
                'lastname' =>'jordans',
                'firstname' => 'mikael',
                'birthday' => '1963-12-11',
                'gender'=> 'Homme',
                'address' => '5 rue du four',
                'zipcode' => '70801',
                'city' => 'montageriy',
                'email' => 'mikael@gmail.com',
                'primaryphone' => '0145667238',
                'secondaryphone' => '',
                'mutual_id' => '9',
                'pension_id' => '9',
            ],
            [
                'id' => 10,
                'lastname' =>'locque',
                'firstname' => 'Justine',
                'birthday' => '1970-12-11',
                'gender'=> 'Femme',
                'address' => '5 rue du four',
                'zipcode' => '70801',
                'city' => 'montageriy',
                'email' => 'Justine@gmail.com',
                'primaryphone' => '0145667238',
                'secondaryphone' => '',
                'mutual_id' => '9',
                'pension_id' => '8',
            ]
        ];
        
        Member::insert($members);
    }
}
