INSERT INTO `pensions` (`id`, `name`, `created_at`, `updated_at`) VALUES
(NULL, 'AG2R', NULL, NULL), 
(NULL, 'AG2R /ARRCO', NULL, NULL), 
(NULL, 'AG2R MSA RSI', NULL, NULL), 
(NULL, 'AGIRC ARRCO', NULL, NULL), 
(NULL, 'ARRCO/MSA', NULL, NULL), 
(NULL, 'Ayant droit (épouse)', NULL, NULL), 
(NULL, 'Ayant droit ?', NULL, NULL), 
(NULL, 'CARMF', NULL, NULL), 
(NULL, 'CARPIMNO', NULL, NULL), 
(NULL, 'CARSAT', NULL, NULL), 
(NULL, 'CARSAT / AG2R', NULL, NULL), 
(NULL, 'CNAV', NULL, NULL), 
(NULL, 'CNRACL - Caisse retraite Hospitaliers Territoriaux', NULL, NULL), 
(NULL, 'CRAM', NULL, NULL), 
(NULL, 'MGEN', NULL, NULL), 
(NULL, 'MGEN/AG2R', NULL, NULL), 
(NULL, 'MSA', NULL, NULL), 
(NULL, 'PRO BTP', NULL, NULL), 
(NULL, 'RSI', NULL, NULL), 
(NULL, 'USA GROUPAMA', NULL, NULL);

INSERT INTO `mutuals` (`id`, `name`, `created_at`, `updated_at`) VALUES
(NULL, 'AG2R', NULL, NULL), 
(NULL, 'ALLIANZ', NULL, NULL), 
(NULL, 'APRIA', NULL, NULL), 
(NULL, 'APRIL', NULL, NULL), 
(NULL, 'ARRCO', NULL, NULL), 
(NULL, 'BPCE Mutuelle', NULL, NULL), 
(NULL, 'CARSAT', NULL, NULL), 
(NULL, 'CNAV', NULL, NULL), 
(NULL, 'EOVI', NULL, NULL), 
(NULL, 'FEMARA', NULL, NULL), 
(NULL, 'GROUPAMA', NULL, NULL), 
(NULL, 'Harmonie mutuelle', NULL, NULL), 
(NULL, 'HUMANIS', NULL, NULL), 
(NULL, 'Intégrance', NULL, NULL), 
(NULL, 'IPSEL- ISANTE', NULL, NULL), 
(NULL, 'MACIF/Almerys', NULL, NULL), 
(NULL, 'MACSF', NULL, NULL), 
(NULL, 'MALAKOFF', NULL, NULL), 
(NULL, 'MGEN', NULL, NULL), 
(NULL, 'MGEN/AG2R', NULL, NULL), 
(NULL, 'MNH Mutuelle Hospitalière', NULL, NULL), 
(NULL, 'Mutualité hospitalier', NULL, NULL), 
(NULL, 'Pacifia', NULL, NULL), 
(NULL, 'PRAGA/APRIA', NULL, NULL), 
(NULL, 'Prévifrance', NULL, NULL), 
(NULL, 'UMR', NULL, NULL), 
(NULL, 'VIA SANTE', NULL, NULL), 
(NULL, 'Via Santé', NULL, NULL), 
(NULL, 'Via santé-AG2R', NULL, NULL), 
(NULL, 'MNH', NULL, NULL);
